rush-02:  main.c rush02.h minor_ten.c ft_twenty_to_ninety.c ft_ten_to_nineteen.c ft_strlen.c ft_strcat.c ft_roller_coaster.c ft_putstr.c ft_open.c ft_check_error.c ft_before_ten.c
	gcc -Wall -Werror -Wextra *.c rush02.h
	mv a.out rush-02
fclean:
	rm -f rush-02
